- name: Instalar paquetes necesarios para Nginx + PHP-FPM
  apt:
    name:
      - nginx
      - php-cli
      - php8.4-fpm
      - php-mysql
      - php-mbstring
      - git
    state: present
    update_cache: yes


- name: Deshabilitar sitio por defecto de nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Crear VirtualHost en Nginx
  template:
    src: etc/nginx/vhost.j2
    dest: /etc/nginx/sites-available/{{ item.name }}
  with_items:
    - "{{ virtualhosts }}"

- name: Crear DocumentRoot si no existe
  ansible.builtin.file:
    path: /{{item["datos"]["documentroot"]}}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items:
    - "{{virtualhosts}}"

- name: Copiar aplicaci贸n Guestbook
  ansible.builtin.copy:
    src: app/
    dest: "/{{ base_web_path }}/"
    owner: www-data
    group: www-data
    mode: '0644'
    directory_mode: '0755'
  
- name: Crear fichero de configuraci贸n config.php dentro de la aplicaci贸n
  ansible.builtin.template:
    src: config.php.j2
    dest: "/{{ base_web_path }}/config.php"
    owner: www-data
    group: www-data
    
- name: Iniciar y habilitar Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Iniciar y habilitar php-fpm
  service:
    name: php8.4-fpm
    state: started
    enabled: yes

- name: Instalar phpmyadmin
  apt:
    pkg:
      - php-mysql
      - php-json
      - php-mbstring
      - php-zip
      - php-gd
      - php-curl
      - php-xml
      - phpmyadmin
    state: latest
    update_cache: yes

- name: Crear VirtualHost para phpMyAdmin
  template:
    src: phpmyadmin.conf.j2
    dest: /etc/nginx/sites-available/phpmyadmin.conf

- name: Activar VirtualHost phpMyAdmin
  file:
    src: /etc/nginx/sites-available/phpmyadmin.conf
    dest: /etc/nginx/sites-enabled/phpmyadmin.conf
    state: link
  notify: restart nginx

- name: Configurar phpMyAdmin con IP de la BD
  template:
    src: config.inc.php.j2
    dest: /etc/phpmyadmin/config.inc.php
    owner: www-data
    group: www-data
    mode: '0644'


- name: Crear enlace simb贸lico
  file:
    src: /etc/nginx/sites-available/{{ item.name }}
    dest: /etc/nginx/sites-enabled/{{ item.name }}
    state: link
  with_items:
    - "{{ virtualhosts }}"
  notify: restart nginx
