- name: Crear base de datos Biblioteca
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Crear usuario MySQL para la aplicaci√≥n Biblioteca
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Copiar dump SQL de Biblioteca al servidor MySQL
  ansible.builtin.copy:
    src: biblioteca.sql
    dest: /tmp/biblioteca.sql


- name: Comprobar si la tabla 'autor' de Biblioteca existe
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: "SHOW TABLES FROM {{ db_name }} LIKE 'autor';"
  register: table_check2


- name: Importar estructura y datos de Biblioteca en MySQL (solo si la tabla no existe)
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: import
    target: /tmp/biblioteca.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
  when: table_check2.query_result[0] | length == 0